name: Build MPlayer for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install automake libtool pkg-config ffmpeg
        brew link ffmpeg --force
        brew install automake libtool pkg-config

    - name: Configure for iOS
      run: |
        export SDK=$(xcrun --sdk iphoneos --show-sdk-path)
        export CC="$(xcrun --sdk iphoneos -f clang)"
        ./configure \
          --disable-gui \
          --enable-static \
          --cc="$CC -isysroot $SDK -arch armv7"
      
    - name: Build MPlayer
      run: |
        make -j$(sysctl -n hw.ncpu)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./build/
