name: Build MPlayer for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install automake libtool pkg-config

    - name: Configure for iOS
      run: |
        export SDK=$(xcrun --sdk iphoneos --show-sdk-path)
        export CC="$(xcrun --sdk iphoneos -f clang)"
        ./configure \
          --disable-gui \
          --disable-mencoder \
          --enable-static \
          --cc="$CC -isysroot $SDK -arch armv7"

    - name: Build MPlayer
      run: |
        make -j$(sysctl -n hw.ncpu)

    - name: List build output
      run: ls -lh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: mplayer-ios
        path: ./mplayer
